import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { API_CONFIG } from '../config/api.config';
import { ApiResponse } from '../models/api-response.model';
import { CreateOrganizationRequest, Organization, OrganizationCourse, OrganizationProgram, OrganizationOverview, OrganizationProfile, OrganizationProfileUpdate, OrganizationStatus, OrganizationMember, UpdateOrganizationRequest, OrganizationProjectDetail, OrganizationProjectMilestone, OrganizationProjectDependency, OrganizationProjectProgress, OrganizationProjectHealth, OrganizationProjectTimelineItem, OrganizationProjectActivity } from '../models/organization.model';
@Injectable({ providedIn: 'root' })
export class OrganizationService {
 private readonly url=`${API_CONFIG.baseUrl}/organizations`; constructor(private readonly http:HttpClient){}
 getMine():Observable<ApiResponse<Organization[]>>{return this.http.get<ApiResponse<Organization[]>>(`${this.url}/me`)} getMyMemberships():Observable<ApiResponse<OrganizationMember[]>>{return this.http.get<ApiResponse<OrganizationMember[]>>(`${this.url}/me/memberships`)} getAll():Observable<ApiResponse<Organization[]>>{return this.http.get<ApiResponse<Organization[]>>(this.url)} create(r:CreateOrganizationRequest):Observable<ApiResponse<Organization>>{return this.http.post<ApiResponse<Organization>>(this.url,r)} createProgram(r:{title:string;slug:string;description?:string;organizationId:string}):Observable<ApiResponse<OrganizationProgram>>{return this.http.post<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs`,r)} update(id:string,r:UpdateOrganizationRequest):Observable<ApiResponse<Organization>>{return this.http.put<ApiResponse<Organization>>(`${this.url}/${id}`,r)} deactivate(id:string):Observable<ApiResponse<void>>{return this.http.delete<ApiResponse<void>>(`${this.url}/${id}`)} getOverview(id:string):Observable<ApiResponse<OrganizationOverview>>{return this.http.get<ApiResponse<OrganizationOverview>>(`${this.url}/${id}/overview`)} getCourses(id:string):Observable<ApiResponse<OrganizationCourse[]>>{return this.http.get<ApiResponse<OrganizationCourse[]>>(`${this.url}/${id}/courses`)} getPrograms(id:string):Observable<ApiResponse<OrganizationProgram[]>>{return this.http.get<ApiResponse<OrganizationProgram[]>>(`${API_CONFIG.baseUrl}/programs/organization/${id}`)}
 getProgramDetail(id:string):Observable<ApiResponse<OrganizationProjectDetail>>{return this.http.get<ApiResponse<OrganizationProjectDetail>>(`${API_CONFIG.baseUrl}/programs/${id}/detail`)} getProgramProgress(id:string):Observable<ApiResponse<OrganizationProjectProgress>>{return this.http.get<ApiResponse<OrganizationProjectProgress>>(`${API_CONFIG.baseUrl}/programs/${id}/progress`)} getProgramHealth(id:string):Observable<ApiResponse<OrganizationProjectHealth>>{return this.http.get<ApiResponse<OrganizationProjectHealth>>(`${API_CONFIG.baseUrl}/programs/${id}/health`)} getProgramTimeline(id:string):Observable<ApiResponse<OrganizationProjectTimelineItem[]>>{return this.http.get<ApiResponse<OrganizationProjectTimelineItem[]>>(`${API_CONFIG.baseUrl}/programs/${id}/timeline`)} getProgramActivity(id:string):Observable<ApiResponse<OrganizationProjectActivity[]>>{return this.http.get<ApiResponse<OrganizationProjectActivity[]>>(`${API_CONFIG.baseUrl}/programs/${id}/activity`)}
 getDependencies(id:string):Observable<ApiResponse<OrganizationProjectDependency[]>>{return this.http.get<ApiResponse<OrganizationProjectDependency[]>>(`${API_CONFIG.baseUrl}/programs/${id}/dependencies`)} createDependency(id:string,b:{predecessorId:string;successorId:string}):Observable<ApiResponse<OrganizationProjectDependency>>{return this.http.post<ApiResponse<OrganizationProjectDependency>>(`${API_CONFIG.baseUrl}/programs/${id}/dependencies`,b)} deleteDependency(id:string):Observable<ApiResponse<void>>{return this.http.delete<ApiResponse<void>>(`${API_CONFIG.baseUrl}/programs/dependencies/${id}`)}
 createMilestone(id:string,b:{title:string;description?:string;dueDate?:string;sortOrder:number}):Observable<ApiResponse<OrganizationProjectMilestone>>{return this.http.post<ApiResponse<OrganizationProjectMilestone>>(`${API_CONFIG.baseUrl}/programs/${id}/milestones`,b)} startMilestone(id:string){return this.http.put<ApiResponse<OrganizationProjectMilestone>>(`${API_CONFIG.baseUrl}/programs/milestones/${id}/start`,{})} completeMilestone(id:string){return this.http.put<ApiResponse<OrganizationProjectMilestone>>(`${API_CONFIG.baseUrl}/programs/milestones/${id}/complete`,{})} blockMilestone(id:string){return this.http.put<ApiResponse<OrganizationProjectMilestone>>(`${API_CONFIG.baseUrl}/programs/milestones/${id}/block`,{})} reopenMilestone(id:string){return this.http.put<ApiResponse<OrganizationProjectMilestone>>(`${API_CONFIG.baseUrl}/programs/milestones/${id}/reopen`,{})} cancelMilestone(id:string){return this.http.put<ApiResponse<OrganizationProjectMilestone>>(`${API_CONFIG.baseUrl}/programs/milestones/${id}/cancel`,{})} deleteMilestone(id:string){return this.http.delete<ApiResponse<void>>(`${API_CONFIG.baseUrl}/programs/milestones/${id}`)}
 publishProgram(id:string){return this.http.put<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs/${id}/publish`,{})} startProgram(id:string){return this.http.put<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs/${id}/start`,{})} pauseProgram(id:string){return this.http.put<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs/${id}/pause`,{})} resumeProgram(id:string){return this.http.put<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs/${id}/resume`,{})} completeProgram(id:string){return this.http.put<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs/${id}/complete`,{})} archiveProgram(id:string){return this.http.put<ApiResponse<OrganizationProgram>>(`${API_CONFIG.baseUrl}/programs/${id}/archive`,{})}
 updateLearningPath(id:string,b:{title:string;description?:string}){return this.http.put<ApiResponse<{id:string;title:string;description:string;programId:string}>>(`${API_CONFIG.baseUrl}/programs/paths/${id}`,b)} addCourseToPath(id:string,b:{courseId:string;sortOrder:number}){return this.http.post<ApiResponse<{id:string}>>(`${API_CONFIG.baseUrl}/programs/paths/${id}/courses`,b)} removeCourseFromPath(pathId:string,courseId:string){return this.http.delete<ApiResponse<void>>(`${API_CONFIG.baseUrl}/programs/paths/${pathId}/courses/${courseId}`)} reorderPathCourse(pathId:string,courseId:string,sortOrder:number){return this.http.put<ApiResponse<unknown>>(`${API_CONFIG.baseUrl}/programs/paths/${pathId}/courses/${courseId}/order`,{sortOrder})}
 publishCourse(id:string){return this.http.put<ApiResponse<OrganizationCourse>>(`${API_CONFIG.baseUrl}/courses/${id}/publish`,{})} archiveCourse(id:string){return this.http.put<ApiResponse<OrganizationCourse>>(`${API_CONFIG.baseUrl}/courses/${id}/archive`,{})}
 getProfile(id:string){return this.http.get<ApiResponse<OrganizationProfile>>(`${this.url}/${id}/profile`)} updateProfile(id:string,b:OrganizationProfileUpdate){return this.http.put<ApiResponse<OrganizationProfile>>(`${this.url}/${id}/profile`,b)} updateStatus(id:string,status:OrganizationStatus){return this.http.put<ApiResponse<OrganizationProfile>>(`${this.url}/${id}/status`,{status})} getMembers(id:string){return this.http.get<ApiResponse<OrganizationMember[]>>(`${this.url}/${id}/members`)} inviteMember(id:string,email:string){return this.http.post<ApiResponse<void>>(`${this.url}/${id}/members/invite`,{email})} deactivateMember(id:string,memberId:string){return this.http.delete<ApiResponse<void>>(`${this.url}/${id}/members/${memberId}`)} activateMember(id:string,memberId:string){return this.http.put<ApiResponse<void>>(`${this.url}/${id}/members/${memberId}/activate`,{})}
}