import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { OrganizationService } from '../../../core/services/organization.service';
import { OrganizationCourse, OrganizationProjectDetail, OrganizationProjectMilestone, OrganizationProjectDependency, OrganizationProjectProgress, OrganizationProjectHealth, OrganizationProjectTimelineItem, OrganizationProjectActivity, OrganizationProjectPath } from '../../../core/models/organization.model';
@Component({selector:'app-organization-project-detail',templateUrl:'./organization-project-detail.component.html',styleUrls:['./organization-project-detail.component.scss']})
export class OrganizationProjectDetailComponent implements OnInit {
 project:OrganizationProjectDetail|null=null; loading=true; error=''; commandAction=''; commandBusy=false;
 pathEditing=''; pathTitle=''; pathDescription=''; pathSaving=false; pathAction=''; pathCreating=false; newPathTitle=''; newPathDescription='';
 courseCatalog:OrganizationCourse[]=[]; courseCatalogLoading=false; courseAction=''; addingCoursePath=''; selectedCourseId=''; courseOrder=0;
 milestoneTitle=''; milestoneDescription=''; milestoneDueDate=''; milestoneSaving=false; milestoneAction='';
 dependencies:OrganizationProjectDependency[]=[]; progress:OrganizationProjectProgress|null=null; progressLoading=true; progressError=''; health:OrganizationProjectHealth|null=null; healthLoading=true; healthError=''; timeline:OrganizationProjectTimelineItem[]=[]; timelineLoading=true; timelineError=''; activities:OrganizationProjectActivity[]=[]; activityLoading=true; activityError=''; dependencyFrom=''; dependencyTo=''; dependencyAction='';
 get milestones():OrganizationProjectMilestone[]{return (this.project as OrganizationProjectDetail & {milestones?:OrganizationProjectMilestone[]})?.milestones||[];}
 get availableCourses():OrganizationCourse[]{const used=new Set(this.project?.learningPaths.flatMap(p=>p.courses.map(c=>c.id))||[]);return this.courseCatalog.filter(c=>!used.has(c.id));}
 constructor(private readonly route:ActivatedRoute,private readonly router:Router,private readonly organization:OrganizationService){}
 ngOnInit():void{this.load();}
 load():void{const id=this.route.snapshot.paramMap.get('programId');if(!id){this.error='Project identifier is missing.';this.loading=false;return;}this.loading=true;this.error='';this.organization.getProgramDetail(id).subscribe({next:r=>{this.project=r.data||null;this.loading=false;this.loadProgress();this.loadHealth();this.loadTimeline();this.loadActivity();this.loadDependencies();this.loadCourseCatalog();},error:e=>{this.error=e?.error?.message||'Unable to load this project.';this.loading=false;}});}
 loadProgress():void{if(!this.project)return;this.progressLoading=true;this.organization.getProgramProgress(this.project.id).subscribe({next:r=>{this.progress=r.data||null;this.progressLoading=false;},error:e=>{this.progressError=e?.error?.message||'Unable to load project learning progress.';this.progressLoading=false;}})}
 loadHealth():void{if(!this.project)return;this.healthLoading=true;this.organization.getProgramHealth(this.project.id).subscribe({next:r=>{this.health=r.data||null;this.healthLoading=false;},error:e=>{this.healthError=e?.error?.message||'Unable to load project health intelligence.';this.healthLoading=false;}})}
 loadTimeline():void{if(!this.project)return;this.timelineLoading=true;this.organization.getProgramTimeline(this.project.id).subscribe({next:r=>{this.timeline=r.data||[];this.timelineLoading=false;},error:e=>{this.timelineError=e?.error?.message||'Unable to load project timeline.';this.timelineLoading=false;}})}
 loadActivity():void{if(!this.project)return;this.activityLoading=true;this.organization.getProgramActivity(this.project.id).subscribe({next:r=>{this.activities=r.data||[];this.activityLoading=false;},error:e=>{this.activityError=e?.error?.message||'Unable to load project activity.';this.activityLoading=false;}})}
 loadDependencies():void{if(!this.project)return;this.organization.getDependencies(this.project.id).subscribe({next:r=>this.dependencies=r.data||[],error:e=>this.dependencyAction=e?.error?.message||'Unable to load dependencies.'})}
 loadCourseCatalog():void{if(!this.project?.organizationId)return;this.courseCatalogLoading=true;this.organization.getCourses(this.project.organizationId).subscribe({next:r=>{this.courseCatalog=r.data||[];this.courseCatalogLoading=false;},error:e=>{this.courseAction=e?.error?.message||'Unable to load organization course catalog.';this.courseCatalogLoading=false;}})}
 createLearningPath():void{
  if(!this.project||!this.newPathTitle.trim()||this.pathCreating)return;
  this.pathCreating=true;this.pathAction='';
  this.organization.createLearningPath(this.project.id,{title:this.newPathTitle.trim(),description:this.newPathDescription.trim()}).subscribe({
   next:()=>{this.newPathTitle='';this.newPathDescription='';this.pathCreating=false;this.load();},
   error:e=>{this.pathAction=e?.error?.message||'Unable to create learning path.';this.pathCreating=false;}
  });
 }
 beginPathEdit(path:OrganizationProjectPath):void{this.pathEditing=path.id;this.pathTitle=path.title;this.pathDescription=path.description||'';this.pathAction='';}
 cancelPathEdit():void{this.pathEditing='';}
 savePath(path:OrganizationProjectPath):void{if(!this.pathTitle.trim()||this.pathSaving)return;this.pathSaving=true;this.pathAction='';this.organization.updateLearningPath(path.id,{title:this.pathTitle.trim(),description:this.pathDescription.trim()}).subscribe({next:()=>{this.pathSaving=false;this.pathEditing='';this.load();},error:e=>{this.pathAction=e?.error?.message||'Unable to update learning path.';this.pathSaving=false;}})}
 openAddCourse(path:OrganizationProjectPath):void{this.addingCoursePath=path.id;this.selectedCourseId='';this.courseOrder=path.courses.length;this.courseAction='';}
 cancelAddCourse():void{this.addingCoursePath='';this.selectedCourseId='';}
 addCourse(path:OrganizationProjectPath):void{if(!this.selectedCourseId)return;this.courseAction='';this.organization.addCourseToPath(path.id,{courseId:this.selectedCourseId,sortOrder:this.courseOrder}).subscribe({next:()=>{this.cancelAddCourse();this.load();},error:e=>this.courseAction=e?.error?.message||'Unable to add course to learning path.'})}
 removeCourse(path:OrganizationProjectPath,courseId:string):void{if(!window.confirm('Remove this course from the learning path?'))return;this.organization.removeCourseFromPath(path.id,courseId).subscribe({next:()=>this.load(),error:e=>this.courseAction=e?.error?.message||'Unable to remove course.'})}
 moveCourse(path:OrganizationProjectPath,index:number,direction:-1|1):void{const next=index+direction;if(next<0||next>=path.courses.length)return;const a=path.courses[index],b=path.courses[next];this.organization.reorderPathCourse(path.id,a.id,b.sortOrder).subscribe({next:()=>this.organization.reorderPathCourse(path.id,b.id,a.sortOrder).subscribe({next:()=>this.load(),error:e=>this.courseAction=e?.error?.message||'Unable to reorder course.'}),error:e=>this.courseAction=e?.error?.message||'Unable to reorder course.'})}
 createDependency():void{if(!this.project||!this.dependencyFrom||!this.dependencyTo||this.dependencyFrom===this.dependencyTo)return;this.dependencyAction='';this.organization.createDependency(this.project.id,{predecessorId:this.dependencyFrom,successorId:this.dependencyTo}).subscribe({next:()=>{this.dependencyFrom='';this.dependencyTo='';this.loadDependencies();this.loadActivity();this.loadHealth();},error:e=>this.dependencyAction=e?.error?.message||'Unable to create dependency.'})}
 deleteDependency(d:OrganizationProjectDependency):void{this.organization.deleteDependency(d.id).subscribe({next:()=>{this.loadDependencies();this.loadActivity();this.loadHealth();},error:e=>this.dependencyAction=e?.error?.message||'Unable to delete dependency.'})}
 createMilestone():void{if(!this.project||!this.milestoneTitle.trim()||this.milestoneSaving)return;this.milestoneSaving=true;this.milestoneAction='';this.organization.createMilestone(this.project.id,{title:this.milestoneTitle.trim(),description:this.milestoneDescription.trim(),dueDate:this.milestoneDueDate||undefined,sortOrder:this.milestones.length}).subscribe({next:()=>{this.milestoneTitle='';this.milestoneDescription='';this.milestoneDueDate='';this.milestoneSaving=false;this.load();},error:e=>{this.milestoneAction=e?.error?.message||'Unable to create milestone.';this.milestoneSaving=false;}})}
 milestoneTransition(m:OrganizationProjectMilestone,action:'start'|'complete'|'block'|'reopen'|'cancel'):void{const calls={start:this.organization.startMilestone,complete:this.organization.completeMilestone,block:this.organization.blockMilestone,reopen:this.organization.reopenMilestone,cancel:this.organization.cancelMilestone};calls[action].call(this.organization,m.id).subscribe({next:()=>this.load(),error:e=>this.milestoneAction=e?.error?.message||'Milestone action failed.'})}
 deleteMilestone(m:OrganizationProjectMilestone):void{if(m.status==='IN_PROGRESS'||m.status==='COMPLETED')return;this.organization.deleteMilestone(m.id).subscribe({next:()=>this.load(),error:e=>this.milestoneAction=e?.error?.message||'Unable to delete milestone.'})}
 projectCommand(action:'publish'|'start'|'pause'|'resume'|'complete'|'archive'):void{if(!this.project||this.commandBusy)return;if(action==='archive'&&!window.confirm('Archive this project? This changes the lifecycle state permanently.'))return;const calls={publish:this.organization.publishProgram,start:this.organization.startProgram,pause:this.organization.pauseProgram,resume:this.organization.resumeProgram,complete:this.organization.completeProgram,archive:this.organization.archiveProgram};this.commandBusy=true;this.commandAction='';calls[action].call(this.organization,this.project.id).subscribe({next:r=>{if(r.data)this.project={...this.project!,status:r.data.status};this.commandBusy=false;this.loadProgress();this.loadHealth();this.loadTimeline();this.loadActivity();},error:e=>{this.commandAction=e?.error?.message||'Project command failed.';this.commandBusy=false;}})}
 refreshWorkspace():void{this.load();} back():void{void this.router.navigate(['/organization']);}
}
